apiVersion: v1
kind: Pod
metadata:
  name: angles-mongo-database
  namespace: angles
  labels:
    app.kubernetes.io/name: angles-mongo-database
spec:
  containers:
  - name: angles-mongo
    image: mongo:4.4.13
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: '1500m'
        memory: '1000Mi'
      requests:
        cpu: '1000m'
        memory: '800Mi'
    ports:
      - containerPort: 27017
        hostPort: 27017
    envFrom:
      - configMapRef:
          name: angles-mongo-config
    env:
      - name: MONGO_ANGLES_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: angles-backend-config
            key: MONGO_ANGLES_PASSWORD
      - name: MONGO_ANGLES_USERNAME
        valueFrom:
          configMapKeyRef:
            name: angles-backend-config
            key: MONGO_ANGLES_USERNAME
    volumeMounts:
      - name: mongo-init
        mountPath: /docker-entrypoint-initdb.d/mongo-init.sh
        subPath: mongo-init.sh
      - mountPath: "/data/db"
        subPath: "./db"
        name: angles-persistent-volume
      - mountPath: "/data/config"
        subPath: "./config"
        name: angles-persistent-volume
  volumes:
    - name: mongo-init
      configMap:
        name: mongo-init
    - name: angles-persistent-volume
      persistentVolumeClaim:
        claimName: angles-persistent-volume-claim

