apiVersion: v1
kind: Service
metadata:
  name: angles-database-service
  namespace: angles
spec:
  selector:
    app.kubernetes.io/name: angles-mongo-database
  type: ClusterIP
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
