apiVersion: v1
kind: Service
metadata:
  name: angles-backend-service
  namespace: angles
spec:
  selector:
    app.kubernetes.io/name: angles-dashboard-backend
  type: ClusterIP
  ports:
    - name: webservice
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: angles-frontend-service
  namespace: angles
spec:
  selector:
    app.kubernetes.io/name: angles-dashboard-frontend
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 3001
      targetPort: 3001
