version: "2.0"

services:
  mongodb:
    container_name: "mongo-angles"
    hostname: mongodb
    image: mongo:4.2.0
    restart: always
    volumes:
        - angles_mongo_db:/data/db
        - angles_mongo_config:/data/configdb
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    ports:
        - 27017:27017
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=@nglesPassword
        - MONGO_INITDB_DATABASE=angles
    command:
        - --auth
        - --bind_ip_all

  backend:
    container_name: "angles"
    image: angleshq/angles:${ANGLES_VERSION}
    restart: always
    ports:
       - 3000:3000
    environment:
       - REACT_APP_SWAGGER_ANGLES_API_URL=127.0.0.1:3000
       - REACT_APP_SWAGGER_SCHEMES=http
       - PORT=3000
    depends_on:
      - mongodb
    volumes:
      -  angles_screenshots:/app/screenshots
      -  angles_screenshot_compares:/app/compares

  frontend:
    container_name: "angles-ui"
    image: angleshq/angles-ui:${ANGLES_VERSION}
    restart: always
    ports:
       - 3001:3001
    environment:
       - REACT_APP_ANGLES_API_URL=http://127.0.0.1:3000
       - PORT=3001
    depends_on:
      - backend

volumes:
 angles_mongo_db:
    name: angles_mongo_db
 angles_mongo_config:
     name: angles_mongo_config
 angles_screenshots:
     name: angles_screenshots
 angles_screenshot_compares:
     name: angels_screenshot_compares
