name: Run Tests
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run Angles unit/integration tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./test/test-setup/docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12

      - name: Setup Angles Mongo Instance
        run: docker-compose up -d

      - name: Trigger tests
        run: MONGO_URL='mongodb://angleshq:%40nglesPassword@127.0.0.1:27017/angles' npm test
